### ISSUE TITLE
导入存档会导致面板直接崩溃

### ISSUE THREAD

**Issue by Orisland** [carrot-hu23/dst-admin-go#37]
如题。
附上log。
https://pste.ch/axebiqacaj.rb
https://pste.ch/zocozukibe.rb

面板版本为群内的1.2.4
系统为Ubuntu22，已经正常运行install_ubuntu.sh，已完成安装。

**Comment by hujinbo23** [comment]
你是不是没有static文件，自己找个其他的版本，把static文件放进去
