### ISSUE TITLE
[BUG]定时任务导致面板断开连接

### ISSUE THREAD

**Issue by TakizawaAnn** [carrot-hu23/dst-admin-go#43]
### 云服面板版本：dst-admin-go.1.2.6

BUG出现的环境条件

- 该 BUG 在**重启 Ubuntu 系统，根据息流教程[https://flowus.cn/share/ed2f7999-b1d4-4d60-9c4d-509ffa578c5a](url)中的步骤启动面板后**出现的。

BUG描述：

- 在面板【定时任务】创建一个定时备份世界的任务后，如下图：

![image](https://github.com/hujinbo23/dst-admin-go/assets/85612262/d5473846-aa62-4598-b734-a6304bfc2dc2)

- 到设定时间点后台面板开始卡住无法操作，刷新页面后显示“错误502”。随后我重启 dst-admin-go 面板后页面恢复正常，接着当我查看【定时任务】中的【上次执行时间】发现没有执行过。

下图是log截取：

![image](https://github.com/hujinbo23/dst-admin-go/assets/85612262/4d342470-c753-4b28-9d15-cc1fbbde21b1)**

**Comment by hujinbo23** [comment]
你是不是配置路径时候 配置了相对路径，不要配置相对路径，使用绝对路径

**Comment by TakizawaAnn** [comment]
> 你是不是配置路径时候 配置了相对路径，不要配置相对路径，使用绝对路径

是的，当我改成绝对路径后它恢复正常了
