### ISSUE TITLE
mod id 2526778484 配置错误

### ISSUE THREAD

**Issue by NightSquirrl** [carrot-hu23/dst-admin-go#55]
如果通过web端进行模组配置，保存配置之后
![image](https://github.com/hujinbo23/dst-admin-go/assets/83497094/b5d5155c-1d38-4fe6-af84-c87d3786f6c4)
该mod在世界设置mod配置中是错误的，世界同样无法启动。
![image](https://github.com/hujinbo23/dst-admin-go/assets/83497094/e141043f-c1f7-4d6d-b1b2-50a4607f06e1)

**Comment by hujinbo23** [comment]
模组配置写法问题，已经修复了，进qq群获取 1.2.8版本，等稳定了在发release
