### ISSUE TITLE
[DSM7.2] Docker安装报错

### ISSUE THREAD

**Issue by DearDavies** [carrot-hu23/dst-admin-go#61]
系统是DSM7.2，我用Container Manager下载好镜像启动的时候报错。
请问大佬，这该怎么解决？

![Snipaste_2024-02-02_09-57-57](https://github.com/hujinbo23/dst-admin-go/assets/43517444/4a4d1661-7128-450f-89f9-c253b17588be)

**Comment by hujinbo23** [comment]
网络问题，多试几遍吧
