### ISSUE TITLE
创意工坊下载mod失效的问题

### ISSUE THREAD

**Issue by PHXMM** [carrot-hu23/dst-admin-go#94]

**Comment by JingHua-ShuiYue** [comment]
用这个项目下载创意工坊的时候一直遇到 `DownloadServerMods timed out with no response from Workshop...` 的问题，然后无聊翻文件发现 steamcmd下Linux64的steamclient.so和/root/dst-dedicated-server/bin64/lib64/steamclient.so文件大小不一致，通过替换文件，然后选择64位启动可以正常下载mod，不知道别人有没有遇到这个问题，我的四台服务器都有这个问题，在这儿分享一下

**Comment by ZaneL1u** [comment]
> Docker 运行的 1.3.1 版本，存在同样问题，按照上述方法已解决，感谢~

大佬，我也在解决这个问题，是把 steamcmd 替换到 dst-dedicated-server 还是？

**Comment by pedestrian0** [comment]
对，用 steamcmd 下 Linux64 的 steamclient.so 替换 dst-dedicated-server/bin64/lib64 下的 steamclient.so

**Comment by ZaneL1u** [comment]
> 对，用 steamcmd 下 Linux64 的 steamclient.so 替换 dst-dedicated-server/bin64/lib64 下的 steamclient.so

谢谢佬！我也行了！
